# Generated by Django 3.1 on 2021-03-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_supplier', models.CharField(max_length=55)),
                ('num_of_people', models.IntegerField()),
                ('heating_source', models.CharField(max_length=55)),
                ('impact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_meals', models.IntegerField()),
                ('veggie_meals', models.IntegerField()),
                ('co_impact', models.DecimalField(decimal_places=3, max_digits=10)),
                ('water_impact', models.DecimalField(decimal_places=3, max_digits=10)),
                ('waste_impact', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
