# Generated by Django 3.1 on 2021-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='veg',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
