# Generated by Django 3.1 on 2021-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impacts', '0002_auto_20210326_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veg',
            name='veggie_meals',
            field=models.CharField(max_length=55),
        ),
    ]
