# Generated by Django 3.1 on 2021-03-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impacts', '0003_auto_20210326_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='name',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='veg',
            name='name',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
